# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0006_order_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_closed',
            new_name='closed',
        ),
    ]
