# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0007_auto_20170927_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishesinorder',
            options={'verbose_name': 'Блюдо в заказе', 'verbose_name_plural': 'Блюда в заказе'},
        ),
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
