# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0003_auto_20170927_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesinorder',
            name='price_per_dish',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='dishesinorder',
            name='total_per_dish',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
